name: 'nextjs-particlex-theme'
description: 'A theme use next.js to generate SSG files for your blog.'
inputs:
  tag:
    description: 'Which theme tag you want to use.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout Main Repository
      uses: actions/checkout@v4
      with:
        repository: IceOfSummer/nextjs-particlex-theme
        ref: ${{ inputs.tag }}
        path: nextjs-particlex-theme

    - name: Checkout Datasource Repository
      uses: actions/checkout@v4
      with:
        path: datasource

    - name: Cache NPM dependencies
      uses: actions/cache@v2
      with:
        path: nextjs-particlex-theme/node_modules
        key: ${{ runner.OS }}-npm-cache
        restore-keys: |
          ${{ runner.OS }}-npm-cache

    - name: Install Dependencies
      run: 'cd nextjs-particlex-theme && npm install'

    - name: Build
      env:
        HEXO_PATH: '../datasource'
      run: 'cd nextjs-particlex-theme && npm run build'

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'nextjs-particlex-theme/out'
